name: Deploy GitHub Page

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
              targets: wasm32-unknown-unknown

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev

        - name: Install trunk
          uses: jetli/trunk-action@v0.5.0
          with:
            version: latest

        - name: Build
          run: trunk build --release

        - name: Optimize
          uses: NiklasEi/wasm-opt-action@v2
          with:
            file: dist/*.wasm

        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            branch: gh-pages
            folder: dist
